[package]
name = "match-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.4"
rust_decimal = "1.35.0"
thiserror = "1.0.60"
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
